[package]
name = "d69_blog_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "sqlite", "macros"] }
