[package]
name = "d54_websocket_server"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
tungstenite = "0.28.0"
