[package]
name = "yew_hello"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.108"
yew = "0.22.0"
web-sys = { version = "0.3.85", features = ["Window"] }

[lib]
crate-type = ["cdylib"]
